{"name": "test_login_successfully", "status": "failed", "statusDetails": {"message": "AssertionError: login failed", "trace": "self = <tests.test_login.LoginTest testMethod=test_login_successfully>\n\n    @allure.story('epic_1') # epic/story of the test case\n    @allure.severity(allure.severity_level.MINOR) # severity of the test case\n    # @pytestrail.case('C48') # test case if on TestRail\n    def test_login_successfully(self):\n        with allure.step('Navigate to login page'):\n            self.homeNavigation.goToLoginPage()\n            self.ts.markFinal(self.loginPage.isAt, \"navigation to login page failed\")\n    \n        with allure.step('Login'):\n            self.loginPage.login(email=td.testData(\"email\"), password=td.testData(\"password\"))\n>           self.ts.markFinal(self.loggedInPage.isAt, \"login failed\")\n\ntests\\test_login.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utilities.teststatus.TestStatus object at 0x000001F8B753C880>, result = False, resultMessage = 'login failed'\n\n    def markFinal(self, result, resultMessage):\n        \"\"\"\n        Mark the final result of the verification point in a test case\n        This needs to be called at least once in a test case\n        This should be final test status of the test case\n        \"\"\"\n        self.setResult(result, resultMessage)\n        if \"FAIL\" in self.resultList:\n            self.resultList.clear()\n>           assert False, resultMessage\nE           AssertionError: login failed\n\nutilities\\teststatus.py:54: AssertionError"}, "steps": [{"name": "Navigate to login page", "status": "passed", "start": 1686795409625, "stop": 1686795410103}, {"name": "Login", "status": "failed", "statusDetails": {"message": "AssertionError: login failed\n", "trace": "  File \"D:\\Python Frameworks selenium\\Python-Test-Automation-Framework\\tests\\test_login.py\", line 36, in test_login_successfully\n    self.ts.markFinal(self.loggedInPage.isAt, \"login failed\")\n  File \"D:\\Python Frameworks selenium\\Python-Test-Automation-Framework\\utilities\\teststatus.py\", line 54, in markFinal\n    assert False, resultMessage\n"}, "start": 1686795410103, "stop": 1686795468715}], "attachments": [{"name": "log", "source": "01829c3c-ea6f-4627-93e1-370f8f6ea861-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "b427547b-ab5b-443b-a212-163b74af5191-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "47e8137d-d6ff-4efc-9a1a-3b777a926d21-attachment.txt", "type": "text/plain"}], "start": 1686795409625, "stop": 1686795468717, "uuid": "a9cb2c5a-44be-47be-b43d-d5f9174ce420", "historyId": "e9f4bee14a43cc6ef574959b962f5cb7", "testCaseId": "e9f4bee14a43cc6ef574959b962f5cb7", "fullName": "tests.test_login.LoginTest#test_login_successfully", "labels": [{"name": "severity", "value": "minor"}, {"name": "story", "value": "epic_1"}, {"name": "tag", "value": "@pytest.mark.usefixtures('oneTimeSetUp', 'setUp')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "DESKTOP-Q4MGKFU"}, {"name": "thread", "value": "15200-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}