{"name": "test_login_successfully", "status": "failed", "statusDetails": {"message": "AssertionError: login failed", "trace": "self = <tests.test_login.LoginTest testMethod=test_login_successfully>\n\n    @allure.story('epic_1') # epic/story of the test case\n    @allure.severity(allure.severity_level.MINOR) # severity of the test case\n    # @pytestrail.case('C48') # test case if on TestRail\n    def test_login_successfully(self):\n        with allure.step('Navigate to login page'):\n            self.homeNavigation.goToLoginPage()\n            self.ts.markFinal(self.loginPage.isAt, \"navigation to login page failed\")\n    \n        with allure.step('Login'):\n            self.loginPage.login(email=td.testData(\"email\"), password=td.testData(\"password\"))\n>           self.ts.markFinal(self.loggedInPage.isAt, \"login failed\")\n\ntests\\test_login.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utilities.teststatus.TestStatus object at 0x000002A4C610C8E0>, result = False, resultMessage = 'login failed'\n\n    def markFinal(self, result, resultMessage):\n        \"\"\"\n        Mark the final result of the verification point in a test case\n        This needs to be called at least once in a test case\n        This should be final test status of the test case\n        \"\"\"\n        self.setResult(result, resultMessage)\n        if \"FAIL\" in self.resultList:\n            self.resultList.clear()\n>           assert False, resultMessage\nE           AssertionError: login failed\n\nutilities\\teststatus.py:54: AssertionError"}, "steps": [{"name": "Navigate to login page", "status": "passed", "start": 1686467927269, "stop": 1686467927605}, {"name": "Login", "status": "failed", "statusDetails": {"message": "AssertionError: login failed\n", "trace": "  File \"D:\\Python Frameworks selenium\\Python-Test-Automation-Framework\\tests\\test_login.py\", line 36, in test_login_successfully\n    self.ts.markFinal(self.loggedInPage.isAt, \"login failed\")\n  File \"D:\\Python Frameworks selenium\\Python-Test-Automation-Framework\\utilities\\teststatus.py\", line 54, in markFinal\n    assert False, resultMessage\n"}, "attachments": [{"name": "login failed.1686467989569.png", "source": "37c7199c-46bc-4078-a53f-c505a5a97e28-attachment.png", "type": "image/png"}], "start": 1686467927605, "stop": 1686467989797}], "attachments": [{"name": "log", "source": "301ab247-8f6e-4b01-a085-0ca48e776e1b-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "8815ef8d-ff05-40a3-bba3-dd2f3b8a4632-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "ac6437de-2bd1-4d28-a831-3e37cfc87c42-attachment.txt", "type": "text/plain"}], "start": 1686467927268, "stop": 1686467989798, "uuid": "af445a86-375e-475d-8d01-bc81b740fdc8", "historyId": "e9f4bee14a43cc6ef574959b962f5cb7", "testCaseId": "e9f4bee14a43cc6ef574959b962f5cb7", "fullName": "tests.test_login.LoginTest#test_login_successfully", "labels": [{"name": "story", "value": "epic_1"}, {"name": "severity", "value": "minor"}, {"name": "tag", "value": "@pytest.mark.usefixtures('oneTimeSetUp', 'setUp')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "DESKTOP-Q4MGKFU"}, {"name": "thread", "value": "16700-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}